name = "amaro"
version = "1.0.0"
description = "Fernet and Branca token encryption for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "jtdowney", repo = "amaro" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
kryptos = ">= 1.4.0 and < 2.0.0"
gleam_time = ">= 1.8.0 and < 2.0.0"
sixtytwo = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
unitest = ">= 1.5.0 and < 2.0.0"
